module.exports = {
	PORTAL_SHOW: require('./portal/show'),
	PORTAL_WEB: require('./portal/web'),
	PORTAL_COMMUNITIES: require('./portal/communities'),
	PORTAL_USER: require('./portal/userpage'),
	PORTAL_POST: require('./portal/posts'),
	PORTAL_FEED: require('./portal/feed'),
	PORTAL_NEWS: require('./portal/notifications'),
	PORTAL_MESSAGES: require('./portal/messages'),
	CTR_SHOW: require('./ctr/show'),
	CTR_WEB: require('./ctr/web'),
	CTR_COMMUNITIES: require('./ctr/communities'),
	CTR_USER: require('./ctr/userpage'),
	CTR_POST: require('./ctr/posts'),
	WEB_ADMIN: require('./admin/home'),
	WEB_API: require('./admin/api'),
};