module.exports = {
	PORTAL_SHOW: require('./console/show'),
	PORTAL_WEB: require('./console/web'),
	PORTAL_COMMUNITIES: require('./console/communities'),
	PORTAL_USER: require('./console/userpage'),
	PORTAL_POST: require('./console/posts'),
	PORTAL_FEED: require('./console/feed'),
	PORTAL_NEWS: require('./console/notifications'),
	PORTAL_MESSAGES: require('./console/messages'),
	WEB_ADMIN: require('./admin/home'),
	WEB_API: require('./admin/api'),
	WEB_LOGIN: require('./web/login'),
	ROBOTS: require('./web/robots'),
	PWA: require('./web/pwa'),
};